final List<Map<String, dynamic>> productItems = [
  {
    'id': 1,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/products/product1.jpg",
      "assets/products/product1.jpg",
      "assets/products/product1.jpg",
      "assets/products/product1.jpg",
    ],
    'category': "clothes",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': "Free Shipping",
    'type': "ad",
  },
  {
    'id': 2,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/products/product2.jpg",
      "assets/products/product2.jpg",
      "assets/products/product2.jpg",
      "assets/products/product2.jpg",
    ],
    'category': "Accessories",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 3,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/products/product3.jpg",
      "assets/products/product3.jpg",
      "assets/products/product3.jpg",
      "assets/products/product3.jpg",
    ],
    'category': "clothes",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': "Free Shipping",
    'type': "ad",
  },
  {
    'id': 4,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/products/product4.jpg",
      "assets/products/product4.jpg",
      "assets/products/product4.jpg",
      "assets/products/product4.jpg",
    ],
    'category': "Accessories",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 5,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/products/product5.jpg",
      "assets/products/product5.jpg",
      "assets/products/product5.jpg",
    ],
    'category': "Decorations",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 5,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/products/product6.jpg",
      "assets/products/product6.jpg",
      "assets/products/product6.jpg",
    ],
    'category': "Electronics",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 6,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/products/product7.jpg",
      "assets/products/product7.jpg",
      "assets/products/product7.jpg",
      "assets/products/product7.jpg",
    ],
    'category': "Electronics",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': "Free Shipping",
    'type': "product",
  },
  {
    'id': 7,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/images/whitejacket.png",
      "assets/images/coloredTop.png",
      "assets/images/whitejacket.png",
      "assets/images/coloredTop.png",
    ],
    'category': "clothes",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': "Free Shipping",
    'type': "ad",
  },
  {
    'id': 8,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': [
      "assets/images/shoes.png",
      "assets/images/shoes.png",
      "assets/images/shoes.png",
      "assets/images/shoes.png",
    ],
    'category': "shoes",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 9,
    'title': "J.Crew T-shirt",
    'price': "25,000 TSH",
    'imageUrl': ["assets/images/braids.png"],
    'description':
        "us elementum. Et ligula ornare tempor fermentum fringil vulputate mi dui. Massa ....",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 10,
    'title': "Hand Jewelry",
    'price': "25,000 TSH",
    'imageUrl': ["assets/images/heinken.png"],
    'description':
        "us elementum. Et ligula ornare tempor fermentum fringil vulputate mi dui. Massa ....",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': "Free Shipping",
    'type': "ad",
  },
  {
    'id': 11,
    'title': "Pink Top",
    'price': "25,000 TSH",
    'imageUrl': ["assets/images/greenwatch.png"],
    'description':
        "us elementum. Et ligula ornare tempor fermentum fringil vulputate mi dui. Massa ....",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 12,
    'title': "Smart Watch",
    'price': "25,000 TSH",
    'imageUrl': ["assets/images/jergens.png"],
    'description':
        "us elementum. Et ligula ornare tempor fermentum fringil vulputate mi dui. Massa ....",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': "Free Shipping",
    'type': "product",
  },
  {
    'id': 13,
    'title': "Earrings",
    'price': "25,000 TSH",
    'imageUrl': ["assets/images/rays.png"],
    'description':
        "us elementum. Et ligula ornare tempor fermentum fringil vulputate mi dui. Massa ....",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': 2000,
    'type': "product",
  },
  {
    'id': 14,
    'title': "Braids",
    'price': "25,000 TSH",
    'imageUrl': ["assets/images/kevita.png"],
    'description':
        "us elementum. Et ligula ornare tempor fermentum fringil vulputate mi dui. Massa ....",
    'rating': 4.5,
    'size': "2xl",
    'color': "Black",
    'shipping': "Free Shipping",
    'type': "ad",
  },
];

final List<Map<String, dynamic>> orderItems = [
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Pending"
  },
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Completed"
  },
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Completed"
  },
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Completed"
  },
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Completed"
  },
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Completed"
  },
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Completed"
  },
  {
    'orderNo': "#0001",
    'customer': "From Juma James",
    'time': "2 days ago",
    'status': "Completed"
  },
];

final List<Map<String, dynamic>> categories = [
  {'name': 'Electronics', 'imageUrl': 'assets/images/Vector.png'},
  {'name': 'Accessories', 'imageUrl': 'assets/images/claritytools.png'},
  {'name': 'Clothes', 'imageUrl': 'assets/images/iconcardigan.png'},
  {'name': 'Shoes', 'imageUrl': 'assets/images/balletshoes.png'},
  {'name': 'Toys & Hobbies', 'imageUrl': 'assets/images/symbolstoys.png'},
  {'name': 'Tools', 'imageUrl': 'assets/images/Group.png'},
  {'name': 'Automotive', 'imageUrl': 'assets/images/iconcar.png'},
  {'name': 'Beauty', 'imageUrl': 'assets/images/iconbeauty.png'},
  {'name': 'Health', 'imageUrl': 'assets/images/solarhealth.png'},
];

final List<Map<String, String>> subscriptions = [
  {
    "type": "Yearly",
    "price": "TZS 300000",
    "duration": "1 year",
    "promotion": "20%",
    "discount": "TZS 140000",
    "trial period": "14 days",
    "priority": "BEST VALUE",
    "status": "Active",
  },
  {
    "type": "6 months",
    "price": "TZS 200000",
    "duration": "6 Months",
    "promotion": "15%",
    "discount": "TZS 120000",
    "trial period": "14 days",
    "priority": "RECOMMENDED",
    "status": "InActive",
  },
  {
    "type": "3 months",
    "price": "TZS 100000",
    "duration": "3 Months",
    "promotion": "10%",
    "discount": "TZS 70000",
    "trial period": "14 days",
    "priority": "",
    "status": "InActive",
  },
];
